### ISSUE TITLE
Update previous post when stream goes offline

### ISSUE THREAD

**Issue by ghost** [Gyoo/Discord-Streambot#11]
Great bot, thanks. It would be nice if the previous post was edited to say the stream is now offline. Edit "Now Live" to "Stream Over" or similar.

**Comment by Gyoo** [comment]
Thanks for the feedback. I have an idea on how to do it, but I can't give an ETA right now as I'm working on #3 and #4 and it will probably take some time because it implies huge changes.

**Comment by ghost** [comment]
Thanks Gyoo. It would be nice if it could de-link the stream too just so it's a bit more compact after the fact for those with link previews on and maintains chat continuity. The channel is fledgling, so the previews kind of clobber the few lines of chat so we've been deleting old streams so chat doesn't look so crazy. Thanks again for the consideration.

![2016-02-11_171214](https://cloud.githubusercontent.com/assets/128811/12996268/3dd5e322-d0e3-11e5-9bf0-8a9a9b1cb86e.png)

**Comment by Gyoo** [comment]
I see what you mean. I have some ideas, but I need to figure out how to edit messages considering the current implementation, which will probably not be the easiest thing to do. Also, I've asked the Discord crew several times to at least shrinken the preview pics for Twitch, but they keep saying "It's on the todo list but there's more important stuff to do before" :/ That's a shame, because I know that this preview pic size is a major problem.

**Comment by Forstride** [comment]
Once this is implemented, it would be nice to have an option to just have it completely delete the message when the stream is over, that way people can easily look through a channel without seeing a bunch of old posts.

Also, I guess to add to this, some kind of command to delete all Streambot messages from a channel (For retroactive support) would be nice.
